spring.application.name=data-service

# Port ch?y Service (Tránh ??ng ?? v?i các module khác c?a DeepReader)
server.port=8081

# --- K?T N?I DATABASE ---
# ?u tiên l?y t? Environment Variable c?a IntelliJ (n?u có).
# N?u không có ho?c bi?n ?ó tr?ng, nó s? dùng MongoDB Local.
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/deepreader_db}

# T? ??ng t?o Index t? @Indexed trong Model User
spring.data.mongodb.auto-index-creation=true

# --- LOGGING DEBUG ---
# Soi câu l?nh Query và thông s? truy?n vào MongoDB ?? debug cho s??ng m?t
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG

# ??m b?o dùng chu?n Reactive cho d? án DeepReader
spring.data.mongodb.repositories.type=reactive