spring.application.name=data-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://23520904_db_user:xrvLmykfIe3lhrae@deep-reader.7s5z2dv.mongodb.net/?appName=deep-reader}
server.port=${DATA_SERVICE_PORT:8081}


