spring.application.name=ai-service
deepreader.qdrant.host=${QDRANT_HOST:3adcc539-6dc7-4ce4-a5cf-cbd08141ca18.us-east-2-0.aws.cloud.qdrant.io}
deepreader.qdrant.grpc-port=${QDRANT_GRPC_PORT:6334}
deepreader.qdrant.api-key=${QDRANT_API_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6ZWU4Yjk1MmEtZTZmZC00ODZkLWEzY2MtNjQzZGVjMmQyMDI0In0.aVPAgxpjy0-ZF_1awOnbqVijpzjzwleTOPrIvl8frIY}
deepreader.qdrant.collection=${QDRANT_COLLECTION:document_chunks}
deepreader.qdrant.timeout-seconds=${QDRANT_TIMEOUT_SECONDS:5}
deepreader.qdrant.vector-size=${QDRANT_VECTOR_SIZE:768}

deepreader.gemini.api-key=${GEMINI_API_KEY:AIzaSyDDl6IJTFW_tC-wDgT8djyhsZixz12Gj24}
deepreader.gemini.embedding-model=${GEMINI_EMBEDDING_MODEL:gemini-embedding-001}
deepreader.gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
deepreader.gemini.embedding-dimensions=${GEMINI_EMBEDDING_DIMENSIONS:768}
