spring.application.name=ai-service
deepreader.qdrant.host=${QDRANT_HOST:https://3adcc539-6dc7-4ce4-a5cf-cbd08141ca18.us-east-2-0.aws.cloud.qdrant.io}
deepreader.qdrant.grpc-port=${QDRANT_GRPC_PORT:6334}
deepreader.qdrant.api-key=${QDRANT_API_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6NGY1NzgzYmEtNWIyZC00NjJkLWFkOTgtODE4MDI5NzkzNGVjIn0.QGNTpk6XormAHEmK4Z-xNdkTQEt62x-iC6rCYwneg_I}
deepreader.qdrant.use-tls=${QDRANT_USE_TLS:true}
deepreader.qdrant.collection=${QDRANT_COLLECTION:document_chunks}
deepreader.qdrant.timeout-seconds=${QDRANT_TIMEOUT_SECONDS:5}
