package com.deepreader.business_service.controller;

import com.deepreader.business_service.client.AiServiceClient;
import com.deepreader.business_service.model.BookChatThreadDeleteCommand;
import com.deepreader.business_service.model.BookFlashcardCommand;
import com.deepreader.business_service.model.BookQueryRequest;
import com.deepreader.business_service.model.BookSummaryCommand;
import com.deepreader.business_service.model.BookUploadResponse;
import com.deepreader.business_service.service.LibraryOrchestrationService;
import com.deepreader.core.model.Book;
import com.deepreader.core.model.ChapterSummary;
import com.deepreader.core.model.ChatHistory;
import com.deepreader.core.model.Flashcard;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.http.MediaType;
import org.springframework.http.codec.multipart.FilePart;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Internal controller for book-related business operations.
 *
 * <p>This controller exposes business-service APIs and delegates the actual
 * workflow to LibraryOrchestrationService. It keeps HTTP request mapping here
 * while orchestration logic stays in the service layer.
 */
@RestController
@RequestMapping(path = "/internal/business/v1/books", produces = MediaType.APPLICATION_JSON_VALUE)
public class LibraryBusinessController {

	private final LibraryOrchestrationService libraryOrchestrationService;

	/**
	 * Creates the controller with the orchestration service used by all endpoints.
	 */
	public LibraryBusinessController(LibraryOrchestrationService libraryOrchestrationService) {
		this.libraryOrchestrationService = libraryOrchestrationService;
	}

	/**
	 * Uploads a book file for a user.
	 *
	 * <p>The file is received as multipart data and passed to the orchestration
	 * layer, where the book can be stored, ingested, and indexed by downstream services.
	 */
	@PostMapping(value = "/upload", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
	public Mono<BookUploadResponse> uploadBook(@RequestParam String userId,
			@RequestParam(required = false) String provider,
			@RequestPart("file") FilePart file) {
		return libraryOrchestrationService.uploadBook(userId, file, provider);
	}

	/**
	 * Lists books, optionally filtered by user ID.
	 *
	 * <p>The userId parameter is optional so internal callers can request either
	 * user-specific books or a broader list depending on their use case.
	 */
	@GetMapping
	public Flux<Book> listBooks(@RequestParam(required = false) String userId) {
		return libraryOrchestrationService.listBooks(userId);
	}

	/**
	 * Deletes a book for a specific user.
	 *
	 * <p>The orchestration service owns the delete workflow, including any cleanup
	 * in other services. A 204 response is returned when the workflow completes.
	 */
	@DeleteMapping("/{bookId}")
	public Mono<ResponseEntity<Void>> deleteBook(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.deleteBook(userId, bookId)
				.thenReturn(ResponseEntity.noContent().build());
	}

	/**
	 * Gets parsed content for a book.
	 *
	 * <p>This returns content generated by the AI service, such as extracted
	 * sections, summaries, and text.
	 */
	@GetMapping("/{bookId}/content")
	public Mono<AiServiceClient.AiDocumentContentResponse> getBookContent(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.getBookContent(userId, bookId);
	}

	/**
	 * Downloads the original source file for a book.
	 *
	 * <p>Multiple media types are declared because source files can be PDFs,
	 * EPUBs, or generic binary files depending on the uploaded document.
	 */
	@GetMapping(value = "/{bookId}/source", produces = {
			MediaType.APPLICATION_PDF_VALUE,
			MediaType.APPLICATION_OCTET_STREAM_VALUE,
			"application/epub+zip"
	})
	public Mono<ResponseEntity<byte[]>> getBookSource(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.getBookSource(userId, bookId);
	}

	/**
	 * Searches inside a book using the provided query request.
	 *
	 * <p>The request is validated before reaching the orchestration layer so
	 * required search input is checked at the API boundary.
	 */
	@PostMapping(value = "/{bookId}/search", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<AiServiceClient.AiSearchResponse> search(@PathVariable String bookId, @RequestParam String userId, @Valid @RequestBody BookQueryRequest request) {
		return libraryOrchestrationService.searchBook(userId, bookId, request);
	}

	/**
	 * Asks a question about a book and returns an AI-generated answer.
	 *
	 * <p>The same query request model is reused because chat and search both need
	 * the user's question and optional retrieval settings.
	 */
	@PostMapping(value = "/{bookId}/chat", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<AiServiceClient.AiChatResponse> chat(@PathVariable String bookId, @RequestParam String userId, @Valid @RequestBody BookQueryRequest request) {
		return libraryOrchestrationService.chatWithBook(userId, bookId, request);
	}

	/**
	 * Generates or retrieves a summary for a book.
	 *
	 * <p>The command object allows callers to pass summary-specific options,
	 * such as provider selection, without exposing orchestration details here.
	 */
	@PostMapping(value = "/{bookId}/summary", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<AiServiceClient.AiSummaryResponse> summary(@PathVariable String bookId, @RequestParam String userId, @Valid @RequestBody BookSummaryCommand command) {
		return libraryOrchestrationService.summarizeBook(userId, bookId, command);
	}

	/**
	 * Generates flashcards for a book.
	 *
	 * <p>The command is validated to ensure flashcard options are acceptable
	 * before the request is sent to the AI and data-service workflow.
	 */
	@PostMapping(value = "/{bookId}/flashcards", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<AiServiceClient.AiFlashcardResponse> flashcards(@PathVariable String bookId, @RequestParam String userId, @Valid @RequestBody BookFlashcardCommand command) {
		return libraryOrchestrationService.generateFlashcards(userId, bookId, command);
	}

	/**
	 * Lists saved summaries for a book.
	 */
	@GetMapping("/{bookId}/summaries")
	public Flux<ChapterSummary> listSummaries(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.listSummaries(userId, bookId);
	}

	/**
	 * Lists saved flashcards for a book.
	 */
	@GetMapping("/{bookId}/flashcards")
	public Flux<Flashcard> listFlashcards(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.listFlashcards(userId, bookId);
	}

	/**
	 * Lists saved chat history for a book.
	 */
	@GetMapping("/{bookId}/chats")
	public Flux<ChatHistory> listChats(@PathVariable String bookId, @RequestParam String userId) {
		return libraryOrchestrationService.listChats(userId, bookId);
	}

	/**
	 * Deletes a chat thread for a book.
	 *
	 * <p>The command identifies which thread should be removed, while the service
	 * layer handles validation and downstream data-service deletion.
	 */
	@PostMapping(value = "/{bookId}/chat-threads/delete", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<ResponseEntity<Void>> deleteChatThread(
			@PathVariable String bookId,
			@RequestParam String userId,
			@RequestBody BookChatThreadDeleteCommand command
	) {
		return libraryOrchestrationService.deleteChatThread(userId, bookId, command)
				.thenReturn(ResponseEntity.noContent().build());
	}

	/**
	 * Adds reading time to a book for a user.
	 *
	 * <p>This endpoint records incremental reading progress instead of replacing
	 * the whole reading session state.
	 */
	@PostMapping("/reading-sessions/add-seconds")
	public Mono<ResponseEntity<Void>> addReadingSeconds(
			@RequestParam String userId,
			@RequestParam String bookId,
			@RequestParam int seconds
	) {
		return libraryOrchestrationService.addReadingSeconds(userId, bookId, seconds)
				.thenReturn(ResponseEntity.noContent().build());
	}

	/**
	 * Edits an existing flashcard.
	 *
	 * <p>The request body is forwarded as a generic object so the data service can
	 * own the exact edit payload contract.
	 */
	@PatchMapping(value = "/flashcards/{cardId}/edit", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<ResponseEntity<Void>> editFlashcard(
			@PathVariable String cardId,
			@RequestParam String userId,
			@RequestBody Object request
	) {
		return libraryOrchestrationService.editFlashcard(userId, cardId, request)
				.thenReturn(ResponseEntity.noContent().build());
	}

	/**
	 * Hides a flashcard without deleting it.
	 *
	 * <p>This supports soft-hide behavior, allowing the card to be removed from
	 * normal views while still letting the data service decide how to store it.
	 */
	@PatchMapping(value = "/flashcards/{cardId}/hide", consumes = MediaType.APPLICATION_JSON_VALUE)
	public Mono<ResponseEntity<Void>> hideFlashcard(
			@PathVariable String cardId,
			@RequestParam String userId,
			@RequestBody Object request
	) {
		return libraryOrchestrationService.hideFlashcard(userId, cardId, request)
				.thenReturn(ResponseEntity.noContent().build());
	}

	/**
	 * Converts downstream WebClient errors into a consistent error response.
	 *
	 * <p>The upstream response body is returned directly when available to avoid
	 * nested JSON strings such as {"error":"{\"error\":\"...\"}"}.
	 */
	@ExceptionHandler(WebClientResponseException.class)
	public ResponseEntity<String> handleUpstreamWebClientError(WebClientResponseException ex) {
		String responseBody = ex.getResponseBodyAsString();

		if (!StringUtils.hasText(responseBody)) {
			responseBody = "{\"error\":\"" + escapeJson(ex.getMessage()) + "\"}";
		}

		HttpStatus status = ex.getStatusCode().is2xxSuccessful()
				? HttpStatus.BAD_GATEWAY
				: HttpStatus.valueOf(ex.getStatusCode().value());

		return ResponseEntity
				.status(status)
				.contentType(MediaType.APPLICATION_JSON)
				.body(responseBody);
	}

	private String escapeJson(String value) {
		if (value == null) {
			return "";
		}

		return value
				.replace("\\", "\\\\")
				.replace("\"", "\\\"")
				.replace("\n", "\\n")
				.replace("\r", "\\r");
	}
}